version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 376597958889.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - docker build -t chainmart-be .
      - docker tag chainmart-be:latest 376597958889.dkr.ecr.ap-southeast-1.amazonaws.com/chainmart-be:latest
  post_build:
    commands:
      - docker push 376597958889.dkr.ecr.ap-southeast-1.amazonaws.com/chainmart-be:latest
