version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: chainmart
      POSTGRES_PASSWORD: Chainmart123@@
    ports:
      - "5432:5432"
    volumes:
      - ./docker-db/postgres:/var/lib/postgresql/data
      # - ./docker-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.20
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: chainmart@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Chainmart123@@
    volumes:
      - ./docker-db/pgadmin:/var/lib/pgadmin
    ports:
      - "10001:80"
