#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

PREFIX=$(echo $(cat $1) | cut -d':' -f1)

# check if have prefix ["feat", "fix", "docs", "style", "refactor", "perf", "test", "chore", "revert"]
if [ "$PREFIX" = "feat" ] || [ "$PREFIX" = "fix" ] || [ "$PREFIX" = "chore" ]; then
  exit 0
else
  echo "Commit message must have prefix [feat, fix, chore]."
  exit 1
fi