#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

PREFIX=$(echo $(git show -s --format=%B) | cut -d':' -f1)

echo "Commit message prefix: $PREFIX"

# PREFIX in ["feat", "fix", "chore"]
if [ "$PREFIX" = "feat" ]; then
  npm version major
elif [ "$PREFIX" = "fix" ]; then
  npm version minor
elif [ "$PREFIX" = "chore" ]; then
  npm version patch
fi

echo "Pushing to remote..."
# wait 5 seconds
sleep 5

echo "Pushing to done..."

exit 0

