#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

PREFIX=$(echo $(git show -s --format=%B) | cut -d':' -f1)

echo "Commit message prefix: $PREFIX"

# PREFIX in ["feat", "fix", "chore"]
if [ "$PREFIX" = "feat" ]; then
  npm version major
  exit 0
elif [ "$PREFIX" = "fix" ]; then
  npm version minor
  exit 0
elif [ "$PREFIX" = "chore" ]; then
  npm version patch
  exit 0
fi
