name: Continuous Development DEV

on:
  push:
    branches:
      - develop

jobs:
  continuous-development:
    name: Continuous Development DEV
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16