name: Continuous Integration

on:
  push:
    branches-ignore:
      - develop
      - production

jobs:
  ci:
    name: Continuous Integration
    runs-on: self-hosted
    steps:
      - name: Run
        run: |
          echo "Not implemented yet"
          echo "The event that triggered this workflow was ${{ github.event_name }}."